name: CI - Build And Run React Testing Library Integration Tests

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      # Required to checkout the code (when any permissions are listed in this section)
      contents: read
      # Required to put a comment into the pull request for vitest-coverage-support-action
      pull-requests: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version: "25.x"

      - name: Install dependencies
        working-directory: ./movie-info-frontend
        run: npm ci
        
      - name: Run React Testing Library unit tests
        working-directory: ./movie-info-frontend
        run: npx vitest --coverage.enabled true --coverage.reporter=json-summary --coverage.reporter=json | tee rtl-output.txt

      - name: Add test results as a PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: ./MovieInfoBackend/TestMovieInfoBackend/rtl-output.txt

      - name: Report unit test coverage
        if: success()
        with:
          working-directory: ./movie-info-frontend
        uses:  davelosert/vitest-coverage-report-action@v2