name: CI - Build And Run React Testing Library Unit Tests

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v6
    - name: Install Node
      uses: actions/setup-node@v6
      with:
        node-version: "25.x"
    - name: Install dependencies
      working-directory: ./movie-info-frontend
      run: npm install
    - name: Run React Testing Library unit tests
      working-directory: ./movie-info-frontend
      run: npx vitest --coverage.enabled true --coverage.reporter=json-summary
    - name: Report unit test coverage
      if: success()
      with:
        working-directory: ./movie-info-frontend
      uses:  davelosert/vitest-coverage-report-action@v2