name: CI - Build And Run xUnit Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read  # For private repos TODO remove me when public
      issues: read  # For private repos TODO remove me when public
      checks: write
      pull-requests: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Set up .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.x'

      - name: Restore dependencies
        run: dotnet restore ./movie-info.sln

      - name: Build the solution
        run: dotnet build ./movie-info.sln --configuration Release --no-restore

      - name: Run unit tests with report
        run: dotnet test ./MovieInfoBackend/TestMovieInfoBackend/TestMovieInfoBackend.csproj -c Release --no-build --logger "xunit;LogFileName=TestOutputResults.xml" --collect:"XPlat Code Coverage" --results-directory test-results

      - name: Publish test results to PR (and other places)
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: (!cancelled())
        with:
          files: |
            ./test-results/**/Test*.xml

      - name: Convert code coverage summary to Markdown format
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: './test-results/*/coverage.cobertura.xml'
          badge: true
          format: 'markdown'
          output: 'both'

      - name: Add code coverage summary as PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: ./code-coverage-results.md

      - name: Write code coverage summary to Job Summary
        run: cat ./MovieInfoBackend/TestMovieInfoBackend/code-coverage-results.md >> $GITHUB_STEP_SUMMARY