name: CI - Build And Run xUnit Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Set up .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.x'

      - name: Restore dependencies
        run: dotnet restore ./movie-info.sln

      - name: Build the solution
        run: dotnet build ./movie-info.sln --configuration Release --no-restore

      - name: Run unit tests with report
        run: dotnet test ./MovieInfoBackend/TestMovieInfoBackend/TestMovieInfoBackend.csproj -c Release --no-build --logger "trx;LogFileName=XUnitTestResults.trx"

      - name: Upload test results
        uses: actions/upload-artifact@v6
        with:
          name: XUnitTestResults
          path: ./MovieInfoBackend/TestMovieInfoBackend/TestResults/XUnitTestResults.trx