
# Made with help from https://playwright.dev/docs/ci#via-containers
name: 'CI - Build And Run Playwright End-To-End Tests'
on:
  push:
    branches:
      - main
  pull_request:  # Just for testing; TODO remove this later
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.58.2-noble  # NOTE: Update this when updating Playwright!
      options: --user 1001

    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version: "25.x"

      - name: Install dependencies
        working-directory: ./movie-info-frontend
        run: npm install

      - name: Run Playwright end-to-end tests
        run: npx playwright test --config ./playwright.config.ts --workers=1
        working-directory: ./movie-info-frontend
        env: 
            E2E_TEST_USE_MOCK_HTTP_CALLS: false
